# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PCA_Geomax_processing
                                 A QGIS plugin
 This plugin process the survey data generated by Geomax
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-07-26
        copyright            : (C) 2022 by Valerio Pinna
        email                : pinnavalerio@yahoo.co.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PCA_Geomax_processing class from file PCA_Geomax_processing.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pca_geomax_survey_processing import PCA_Geomax_processing
    return PCA_Geomax_processing(iface)
